--- 
title: "NYC Arrests"
author: "Ryan Rogers and Tyler Marshall"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

## Overview of analysis:

In this project, we are interested in looking at trends in arrests made by the NYPD over the last decade, and seeing how they have evolved over time in the face of various political, social, and societal changes. In the process, we will explore various events and cycles, and see how they can have an impact on arrests. We are very interested in learning more about the city we are living in, and better understanding how it continues to change and evolve up to the present day. There is always a lot going on in New York, so we are excited to discover the interesting correlations that can be discovered between arrests and different events. Additionally, we wanted to get a better understanding of how things have changed over the past 10 years, and uncover the long term-trends that can be observed. 

Here are some areas we will explore:

1. The past fifteen years have heralded a whirlwind of events. Since 2006, we have had a major economic recession and recovery, a worldwide pandemic, and many legislative developments, such as the legalization of marijuana and same-sex marriage. These are events that impact people’s lives – and we would like to explore how this impact manifests itself specifically in the form of arrests. It might be reasoned that ‘positive’ events, economic or otherwise, would lead to fewer arrests – is this the case?
  a. How do major events, such as elections, lockdowns, and legalizations/decriminalization impact the arrest rate in NYC? Are certain demographics, or types of crimes, more impacted than others?
  b. How do minor events, such as won or lost sports games, parades, and other public gatherings impact local numbers of arrests in NYC? What crimes tend to be more common around certain events? Is this what we would expect or is something surprising going on in the data?
2. How do external trends impact the rates of arrest for certain crimes? For example, have there been fewer drunk driving arrests since apps such as Uber and Lyft have made their debut?
3. It is certain that every crime committed does not correspond to exactly one arrest. We are interested to explore any patterns in discrepancies between crimes committed and arrests made.
  a. Which crimes have the highest arrest rates, relative to the number of crimes of the type committed?
  b. Are there clear patterns of bias present in the arrests made in NYC?
4. Are there interesting conclusions to be found in the more mundane details of New York City life? For instance, which days of the week see the most arrests? Which months?
  
Now that we've given some background on what we want to do with this project, let's dive in to the data that we'll be using in our analysis.