<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Results | NYC Arrests</title>
  <meta name="description" content="Chapter 5 Results | NYC Arrests" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Results | NYC Arrests" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Results | NYC Arrests" />
  
  
  

<meta name="author" content="Ryan Rogers and Tyler Marshall" />


<meta name="date" content="2021-12-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="missing-values.html"/>
<link rel="next" href="interactive-component.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">NYC Arrests</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#overview-of-analysis"><i class="fa fa-check"></i><b>1.1</b> Overview of analysis:</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-sources.html"><a href="data-sources.html"><i class="fa fa-check"></i><b>2</b> Data sources</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-sources.html"><a href="data-sources.html#arrest-data"><i class="fa fa-check"></i><b>2.1</b> Arrest Data</a></li>
<li class="chapter" data-level="2.2" data-path="data-sources.html"><a href="data-sources.html#crime-data"><i class="fa fa-check"></i><b>2.2</b> Crime Data</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>3</b> Data transformation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-transformation.html"><a href="data-transformation.html#crime-data-1"><i class="fa fa-check"></i><b>3.1</b> Crime Data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-transformation.html"><a href="data-transformation.html#data-import---2021-data"><i class="fa fa-check"></i><b>3.1.1</b> Data Import - 2021 Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-transformation.html"><a href="data-transformation.html#data-import---2006-2021-data"><i class="fa fa-check"></i><b>3.1.2</b> Data Import - 2006-2021 Data</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-transformation.html"><a href="data-transformation.html#combining-old-and-new"><i class="fa fa-check"></i><b>3.1.3</b> Combining Old and New</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-transformation.html"><a href="data-transformation.html#aggregating-by-category"><i class="fa fa-check"></i><b>3.1.4</b> Aggregating by Category</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="missing-values.html"><a href="missing-values.html"><i class="fa fa-check"></i><b>4</b> Missing values</a>
<ul>
<li class="chapter" data-level="4.1" data-path="missing-values.html"><a href="missing-values.html#investigating-missing-values"><i class="fa fa-check"></i><b>4.1</b> Investigating Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>5</b> Results</a>
<ul>
<li class="chapter" data-level="5.1" data-path="results.html"><a href="results.html#initial-exploration"><i class="fa fa-check"></i><b>5.1</b> Initial Exploration</a></li>
<li class="chapter" data-level="5.2" data-path="results.html"><a href="results.html#arrests-compared-to-crime"><i class="fa fa-check"></i><b>5.2</b> Arrests Compared to Crime</a></li>
<li class="chapter" data-level="5.3" data-path="results.html"><a href="results.html#arrests-related-to-marijuana-over-time"><i class="fa fa-check"></i><b>5.3</b> Arrests Related to Marijuana over time</a></li>
<li class="chapter" data-level="5.4" data-path="results.html"><a href="results.html#arrests-near-elections"><i class="fa fa-check"></i><b>5.4</b> Arrests near Elections</a></li>
<li class="chapter" data-level="5.5" data-path="results.html"><a href="results.html#thanksgiving-day-parade---more-arrests-or-fewer"><i class="fa fa-check"></i><b>5.5</b> Thanksgiving Day Parade - More arrests, or fewer?</a></li>
<li class="chapter" data-level="5.6" data-path="results.html"><a href="results.html#have-drunk-driving-arrests-gone-down-recently"><i class="fa fa-check"></i><b>5.6</b> Have Drunk Driving Arrests Gone Down Recently</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="interactive-component.html"><a href="interactive-component.html"><i class="fa fa-check"></i><b>6</b> Interactive component</a></li>
<li class="chapter" data-level="7" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>7</b> Conclusion</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">NYC Arrests</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="results" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> Results</h1>
<div id="initial-exploration" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Initial Exploration</h2>
<p>In this section, we will be sharing the results of exploratory analysis with our data. We will be focusing on the findings that we found most interesting during this process while also trying to provide some insight into some of the questions of interest mentioned at the beginning of this project. To start, we made some basic bar charts to get a better understanding of the arrests occurring in New York City. First, we looked at how the number of arrests has changed over the past 10 years.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>From the plot above, we can see that the number of arrests has decreased each year for the past 10 years. The decrease in arrests is very significant as well since there were over 400,000 arrests in 2011 while there were under 150,000 arrests in 2020 and just over 100,000 arrests so far in 2021. It seems likely that the impact of COVID-19 has helped decrease the number of arrests in 2020 and 2021, especially in 2020 with so many things being shutdown. It will be interesting to see if the number of arrests in 2021 is larger than the 2020 which would be a deviation from the trend of arrests going down. While this plot indicates progress in terms of safety in New York, it will be interesting to see if the number of crimes has dropped significantly as well. If arrests are going down, but crimes are not, then this would indicate that the city is not actually safer, but instead people are getting away with more crimes. We were also interested in looking at the distribution of arrests by month to see if this varied throughout the year. From the plot below, we see that there doesn’t seem to be significant variation from month to month in terms of arrests over the past 10 years.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>One small pattern that we can see from this plot is that the number of arrests seems to drop off a little in December, with December 2014 being the most extreme example. The reasoning for this drop off is unclear, but it could potentially be related to the holiday season. It will be interesting to compare to the number of crimes in December to see if people commit fewer crimes at the end of the year. Another aspect of this plot that we found interesting is that the number of arrests really drops off in 2020 once COVID hit. April, June, and July all had very low arrest totals and this was likely due to the fact that most people were quarantining and not going out much.</p>
<p>We also wanted to look at individual days to see if there may be a reason certain days had such levels of crime. We created a Cleveland dot plot to look at the 30 days with the highest arrest totals in the past 10 years.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>From the plot above, we see that the most arrests in one day over the past 10 years was 1750 on March 7th, 2012. There doesn’t seem to be anything in particular that explains why there were so many arrests on this day since it was a seemingly ordinary Wednesday in March. This was one of two days with more than 1700 arrests, with the other being February 1st, 2012 which also happened to be a Wednesday. It is also interesting to see that all of these days were either in 2011, 2012, or 2013. This makes sense given what the bar plot above showed us in terms of arrests by year, but it is still interesting to see that there were no days recently that made it in the top 30. When looking at the days on this list, we also noticed that most of these days occurred earlier in the year. Only one of the 30 days occurred in the second half of the year which seems a bit odd considering that there wasn’t a huge difference between the number of arrests by month. It would be interesting to see if this pattern continued for the top 50 or 100 days in terms of most arrests, and if there is a potential explanation for why this is the case. Another interesting point is the weekdays on which the most arrests occurred. As we can see, all of the top days were Wednesdays, Thursdays, and Fridays. It may be argued that Weekends typically see less activity, as they may see fewer people commuting into the city. It is quite curious, though, that Mondays and Tuesdays are under-represented.</p>
<p>We also want to look at the types of arrests that are occurring in New York City. The three types of arrests according to the data dictionary are felonies, misdemeanors, and violations. A bar plot showing how common each arrest type has been over the past 10 years is below.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>From the bar plot above, we can see that misdemeanor is the most common type of arrest in our dataset with over 2 million arrests that were related to misdemeanor charges. Felony is the next most common type of arrest with just under 1 million arrests while violations only account for around 200,000 arrests. There is also a small portion of arrests classified as <code>I</code>, which denotes infractions. There were also a small amount of arrests that did not have a <code>LAW_CAT_CD</code>, so these were categorized as <code>NA</code> in our plot.</p>
<p>Next, we made a parallel coordinates plot to get a better understanding of the arrests made in each borough. We categorized the types of arrests into five categories: Murder, Rape, Aggravated Assault, Motor Vehicle Theft, and Robbery.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>From the parallel coordinates plot, Richmond County (Staten Island) has had the fewest number of arrests in all of these categories over the past 10 years. This is not surprising since Staten Island is the least populated of the five boroughs. The Bronx has had the most arrests related to murder with over 3500 in the past 10 years, but did not have the most arrests in any of the other four categories. Kings County (Brooklyn) had the most arrests related to rape, aggravated assault, motor vehicle theft, and robbery since 2011. While Kings County had the most arrests in all of these categories, the number of arrests varied significantly. Aggravated assault had almost 50,000 arrests and robbery had around 35,000 while there were just over 5000 arrests for rape and 3500 for motor vehicle theft. Queens County did not have the most or fewest arrests in any category, but almost had as many motor vehicle thefts as Kings County. Finally, New York County had the second fewest arrests for murder, rape, aggravated assault, and motor vehicle theft.</p>
</div>
<div id="arrests-compared-to-crime" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Arrests Compared to Crime</h2>
<p>Earlier in this analysis, we mentioned how arrests can be considered a proxy for crime, but that this equivalence is not perfect. To begin, we will put this assumption to the test by comparing our data on arrests in New York City to our data on reported NYC crime. In the below visuals, we see reported crimes of several categories, paired with their associated arrests. We first look at general crime aggregates, compared to arrests.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This reveals a concerning discrepancy. According to our crime reports, indexed crimes have remained stable over the past 10 years. Arrests, however, have decreased steadily over time! This would suggest that police have been making fewer arrests, relative to crime. Many media sources (Ex: <a href="https://www.usatoday.com/story/opinion/policing/2021/04/09/violent-crime-surged-across-america-after-police-retreated-column/7137565002/" class="uri">https://www.usatoday.com/story/opinion/policing/2021/04/09/violent-crime-surged-across-america-after-police-retreated-column/7137565002/</a>), have suggested this decrease can be attributed to increased police caution following the highly publicized killings of several Black men, starting in 2013, and the rise of the Black Lives Matter Movement. Notably, one of these killings, the 2014 killing of Eric Garner, was the result of NYPD action. Going further, it seems that there were changes in police policy after what seemed to be a retaliatory attack against the NYPD in December of 2014 (<a href="https://nypost.com/2014/12/29/arrests-plummet-following-execution-of-two-cops/" class="uri">https://nypost.com/2014/12/29/arrests-plummet-following-execution-of-two-cops/</a>). It is hard to gauge whether this decline can be solely attributed to this increased police caution, or if part of the decline in arrests was due to an ongoing pattern that extends further back in time. Regardless, it seems apparent that arrests have declined steadily over time, while the crimes included in the UCR’s crime index have remained relatively steady.</p>
<p>We have established that crimes and arrests are not equivalent, but how large is the discrepancy for individual categories of crime, and are these discrepancies consistent across boroughs? In the below visual, columns are grouped by their year and associated county (NY for New York, Kn for Kings, Rc for Richmond, Br for Brooklyn, and Qn for Queens).</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>There are some very interesting things to be observed here. First, arrests do not map exactly to reported crimes. Aggravated Assault, Murder, and Motor Vehicle Theft all present cases where the number of arrests does not exactly match the associated number of crimes reported. Rape seems the exception, with arrest counts closer to crime reports. Next, it is interesting to note that the degree to which arrests differ from crime reports, and the direction of the mismatch, varies. In the case of motor vehicle theft, crime reports outpace arrests by a large degree. This makes sense, considering that many motor vehicle thefts occur when the vehicle owner is not present. Since motor vehicle theft often has the criminal and the victim at different locations during the time of the crime, it is reasonable that it may be harder to make an arrest after the crime, since fewer details may be known about the criminal. One confusing relation is the relation between murder arrests and reports. It seems counter-intuitive that the number of arrests made would exceed the number of murders committed. Perhaps this can be attributed to arrests made before the actual criminal was determined. Once again, we have a case where the victim cannot report effectively regarding details of the criminal, but with a crime considered to be more severe.
In general, however, arrests seem to exhibit values similar to crime reports. One of the primary lessons from this visual is the understanding that arrest data can serve as a proxy for crime data, but should be recognized as a different metric, and prone to distortion.</p>
</div>
<div id="arrests-related-to-marijuana-over-time" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Arrests Related to Marijuana over time</h2>
<p>Since 2011, there have been several changes in the legal status of marijuana in New York City, and it is now legalized in the city as of 2021. Prior to this, however, there were many legal events that softened or removed penalties on marijuana-related offenses. Among them are these events:</p>
<ul>
<li>November 19th, 2014: Mayor de Blasio launches a policy initiative related to marijuana possession. Under this initiative, individuals in possession of 25 or fewer grams of marijuana are fined, rather than arrested. (<a href="https://nypost.com/2014/11/10/nyc-may-stop-making-arrests-for-small-amounts-of-marijuana/" class="uri">https://nypost.com/2014/11/10/nyc-may-stop-making-arrests-for-small-amounts-of-marijuana/</a>)</li>
<li>July 31st, 2018: The Manhattan District Attorney ends the prosecution of marijuana possession and smoking. (<a href="https://www.manhattanda.org/tomorrow-d-a-vance-ends-prosecution-of-marijuana-possession-and-smoking-cases/" class="uri">https://www.manhattanda.org/tomorrow-d-a-vance-ends-prosecution-of-marijuana-possession-and-smoking-cases/</a>)</li>
<li>September 1st, 2018: The NYPD ceases arrests of individuals smoking marijuana, opting instead to issue summonses instead. (<a href="https://www.ny1.com/nyc/all-boroughs/news/2018/09/01/nypd-marijuana-enforcement-relaxation-policy-takes-effect-most-marijuana-smokers-to-get-summonses" class="uri">https://www.ny1.com/nyc/all-boroughs/news/2018/09/01/nypd-marijuana-enforcement-relaxation-policy-takes-effect-most-marijuana-smokers-to-get-summonses</a>)</li>
<li>July 29th, 2019: Governor Cuomo signs legislation reducing penalties for marijuana (<a href="https://www.forbes.com/sites/lisettevoytko/2019/07/29/new-york-decriminalizes-recreational-marijuana-falls-short-of-governors-goal-to-legalize/?sh=165b0ab4ee70" class="uri">https://www.forbes.com/sites/lisettevoytko/2019/07/29/new-york-decriminalizes-recreational-marijuana-falls-short-of-governors-goal-to-legalize/?sh=165b0ab4ee70</a>)</li>
<li>March 31, 2021: Marijuana is legalized in New York State (<a href="https://cannabis.ny.gov/marihuana-regulation-and-taxation-act-mrta" class="uri">https://cannabis.ny.gov/marihuana-regulation-and-taxation-act-mrta</a>)</li>
</ul>
<p>Below is a time series graph depicting marijuana-related arrests, annotated with these events.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>There are some very interesting observations here. As can be observed, there was a tremendous drop in marijuana arrests after the launch of Mayor de Blasio’s November 19th, 2014 policy initiative. However, this short-term decrease did not last. Though marijuana arrests show a marked decrease after the initiative as compared to before, arrests did see a rebound in 2015. The next largest decline appears to begin around January 2018, though the cause of this decline is not immediately obvious. It may be linked to a more widespread acceptance of marijuana that year, as evident in the commissioning of a study on the legalization of marijuana commissioned by Governor Cuomo that January (<a href="https://www.nysenate.gov/newsroom/press-releases/jamaal-t-bailey/marijuana-legalization-impact-assessment-study" class="uri">https://www.nysenate.gov/newsroom/press-releases/jamaal-t-bailey/marijuana-legalization-impact-assessment-study</a>). Further developments later that year solidify this direction, such as the aforementioned end of prosecution in several boroughs, and the end of arrests for smoking. Unlike the previous decline, this second drop in arrests would not see a rebound, and arrests end entirely after the March 31st, 2021 legalization. The reasons for earlier declines in 2011 and 2012 are not as easy to explain, but it should be noted that 2011 was a high point in marijuana arrests. (<a href="https://gothamist.com/news/nyc-still-marijuana-arrest-capital-of-the-world-arrests-rose-again-last-year" class="uri">https://gothamist.com/news/nyc-still-marijuana-arrest-capital-of-the-world-arrests-rose-again-last-year</a>)</p>
<p>While marijuana was still illegal, and the cause of many arrests, many critics of marijuana laws claimed that one of the main victims of these laws were young men of color, who were arrested and often jailed at higher rates as a consequence of these laws. Is this actually the case? Below is a visual that looks at data from 2011-2013 (inclusive), before any major policy actions we have discussed.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-12-1.png" width="960" /></p>
<p>This graph yields a very interesting result. Though it seems apparent that young, non-white people are the demographic with the most marijuana arrests, as was contended in the past, it would seem that the ratio of white to non-white arrests is more skewed with older, rather than younger individuals. That is, though people of color under 44 represent the largest group of marijuana arrests, older individuals arrested for marijuana offenses tended to be more non-white, relative to the ratio seen with younger arrests. This pattern seems to present itself most prominently among Black individuals. We can confirm that this distortion is present through a Chi-Squared test.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="results.html#cb1-1" aria-hidden="true" tabindex="-1"></a>Chi_mj_arrests_mosaic <span class="ot">&lt;-</span> {</span>
<span id="cb1-2"><a href="results.html#cb1-2" aria-hidden="true" tabindex="-1"></a>  nyc_mj_arrests_mosaic <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="results.html#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(AGE_GROUP, PERP_RACE) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="results.html#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">Freq =</span> <span class="fu">sum</span>(Freq)) <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="results.html#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">&#39;PERP_RACE&#39;</span>, <span class="at">values_from =</span> <span class="st">&#39;Freq&#39;</span>)</span>
<span id="cb1-6"><a href="results.html#cb1-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-7"><a href="results.html#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(Chi_mj_arrests_mosaic) <span class="ot">&lt;-</span> Chi_mj_arrests_mosaic<span class="sc">$</span>AGE_GROUP</span>
<span id="cb1-8"><a href="results.html#cb1-8" aria-hidden="true" tabindex="-1"></a>Mat_mj_arrests_mosaic <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(Chi_mj_arrests_mosaic[<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>])</span>
<span id="cb1-9"><a href="results.html#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="results.html#cb1-10" aria-hidden="true" tabindex="-1"></a>chi_results <span class="ot">&lt;-</span><span class="fu">chisq.test</span>(Mat_mj_arrests_mosaic, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-11"><a href="results.html#cb1-11" aria-hidden="true" tabindex="-1"></a>chi_results</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  Mat_mj_arrests_mosaic
## X-squared = 2606.6, df = 16, p-value &lt; 2.2e-16</code></pre>
<p>The exact reason this pattern is present seems an interesting avenue for speculation, as it seems difficult to reason why older people of color, especially Black individuals, would be more likely to be arrested for marijuana crimes, relative to younger people of color.</p>
</div>
<div id="arrests-near-elections" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Arrests near Elections</h2>
<p>We also want to look to see if the number of arrests typically changes around elections. The three Presidential elections in the past 10 years occurred on November 3rd, 2020, November 8th, 2016, and November 6th, 2012. First, we are going to look at the number of arrests on these days compared to the average number of arrests per day in each of these respective years.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Arrest Year
</th>
<th style="text-align:center;">
Average Number of Arrests per day
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
2012
</td>
<td style="text-align:center;">
1082.73
</td>
</tr>
<tr>
<td style="text-align:center;">
2016
</td>
<td style="text-align:center;">
860.28
</td>
</tr>
<tr>
<td style="text-align:center;">
2020
</td>
<td style="text-align:center;">
383.64
</td>
</tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Arrest Date
</th>
<th style="text-align:center;">
Number of Arrests
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
2012-11-03
</td>
<td style="text-align:center;">
479
</td>
</tr>
<tr>
<td style="text-align:center;">
2016-11-08
</td>
<td style="text-align:center;">
734
</td>
</tr>
<tr>
<td style="text-align:center;">
2020-11-06
</td>
<td style="text-align:center;">
384
</td>
</tr>
</tbody>
</table>
<p>When looking at the number of arrests on Presidential election days, the number of arrests on the 2012 election day was much lower than the average day that year. The average number of arrests on a day in 2012 was 1082.7, but only 479 arrests occurred on November 6th, 2012. In 2016, the average number of arrests was 860.3, but only 734 occurred on election day in 2016. This is not as a large of a drop in 2012, but it still is lower than the average day. This trend did not hold in 2020 as the average number of arrests was 383.6, and 384 arrests occurred on November 3rd, 2020.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Arrest Date
</th>
<th style="text-align:center;">
Number of Arrests
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
2012-11-04
</td>
<td style="text-align:center;">
439
</td>
</tr>
<tr>
<td style="text-align:center;">
2016-11-09
</td>
<td style="text-align:center;">
868
</td>
</tr>
<tr>
<td style="text-align:center;">
2020-11-07
</td>
<td style="text-align:center;">
364
</td>
</tr>
</tbody>
</table>
<p>Not only do we want to look at the arrests on election day, but we also wanted to look at the day after the election. We want to see if the results of the election potentially lead to more arrests the next day. On November 4th 2012, 439 arrests occurred which is even fewer than the 479 that occurred on election day, and again well below the average for the year. In 2016, 868 arrests happened the day after the election, which was just barely above the daily average of 860.3 in that year. Finally, on November 8th 2020, 364 arrests were made which was slightly below the average of 383.6 arrests. There does not seem to be a major pattern in terms of arrest during election periods. It was interesting to see that the number of arrests was well below average in 2012 during these election days, but this pattern didn’t seem to hold in 2016 and 2020.</p>
</div>
<div id="thanksgiving-day-parade---more-arrests-or-fewer" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Thanksgiving Day Parade - More arrests, or fewer?</h2>
<p>Many of the events discussed so far have been fairly prominent occurrences, with the ability to affect arrest rates over long periods of time. However, these are not the only events that occur in New York City. Many of these other events are smaller in scope, and less historical, but do provide another interesting perspective on how circumstance can impact numbers of arrests. Let us consider NYC’s annual Thanksgiving Day parade. This annual event sees thousands of residents and tourists gather to spectate a common experience. Along with these throngs come an increased police presence, and possible opportunities for criminals. The question remains then, how does the Thanksgiving Thursday compare to any other November Thursday? See below a map of thefts in New York City on Thanksgiving Day (on the left), and the Thursdays prior (on the right) with the parade route shown in blue.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The results are somewhat unexpected. It may seem intuitive to suspect elevated levels of crime, and therefore arrests around the parade route, but this does not seem to be the case. Many of the areas on the parade route, in fact, see little to no arrests the day of the parade! In fact, it appears that arrests in general are significantly lower on Thanksgiving day compared to the Thursday prior. If more evidence was needed, look at the following box plot, which compares the numbers of arrests on Thanksgiving days, compared to the Thursday prior.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="have-drunk-driving-arrests-gone-down-recently" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Have Drunk Driving Arrests Gone Down Recently</h2>
<p>Our next exploration is looking at arrests related to drunk driving. We wanted to see if the creation of apps like Uber and Lyft has helped limit the number of drunk driving arrests. To do this, we looked at the number of drunk driving arrests in each of the past 10 years.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>From the plot above, we can see an interesting trend in terms of drunk driving arrests over the past 10 years. There is a clear increase in arrests during 2013 and 2014 related to drunk driving before it drops off in subsequent years. There is a sharp drop in number of arrests in 2020 and so far in 2021 which is likely due to the pandemic. As noted on the plot, Lyft was started in 2012 while Uber was created in 2009. These apps didn’t seem to have much impact on drunk driving arrests initially, but could have had some impact once they got larger and became more well-known. There has been a progressive decrease in drunk driving arrests since 2015/2016 which is likely due to a combination of the growth of these apps as well as more awareness towards drunk driving. Even if the reasoning for the drop off is not completely clear, it is a good sign that the number of drunk driving arrests has gone down in recent years.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="missing-values.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="interactive-component.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Tylermarshall21/NYCArrests/edit/main/05-results.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/Tylermarhall21/NYCArrests/blob/main/05-results.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
